[build]
  publish = "public"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "12"
  publish = "dist"
  functions = './functions/'

[[plugins]]
  package = "netlify-plugin-gatsby-cache"