backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

# Uncomment local_backend when you need to develop in your local
#local_backend: true # run npx netlify-cms-proxy-server for local testing

media_folder: "static/assets" 
public_folder: "/assets" 

collections:
  - name: 'vlogit' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Vlogit' # Used in the UI
    label_singular: 'Vlogi' # Used in the UI, ie: "New Post"
    description: >
      Mahtava sisältösi!
    folder: 'src/content/vlogit'
    slug: '{{year}}-{{day}}-{{month}}-{{slug}}'
    summary: '{{title}} — {{year}}/{{day}}/{{month}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: 'Template', name: 'template', widget: 'hidden', default: 'vlog-post'}
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Slug', name: 'slug', widget: 'string', hint: 'Start slug with /. Use only alphanumeric characters, - and _. Avoid spaces in any cases.'}
      - {
          label: 'Julkaisupäivä',
          name: 'date',
          widget: 'datetime',
          dateFormat: 'DD-MM-YYYY',
          timeFormat: 'HH:mm',
           format: 'DD-MM-YYYY HH:mm',
        }
      - { label: 'SEO Description', name: 'description', widget: 'text' }
      - {
          label: 'Vlogin kuva',
          name: 'featuredImage',
          widget: 'image',
          required: false,
          tagname: ''
        }
      - { label: 'Youtube url', name: 'videoUrl', widget: 'file', required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/content/pages/index.md"
        fields:
        - {label: "Template", name: "template", widget: "hidden", default: "index-page" }
        - {label: "Slug", name: "slug", widget: "hidden", default: "/" }
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Tagline", name: "tagline", widget: "string"}
        - {label: "Featured Image", name: "featuredImage", widget: "image"}
        - {label: "Body", name: "body", widget: "markdown"}
        - label: "CTA"
          name: "cta"
          widget: "object"
          fields: 
            - name: "ctaText"
              label: "CTA text"
              widget: "string"
            - name: "ctaLink"
              label: "CTA Link"
              widget: "string"
      - label: "Metsän Otus"
        name: "metsan-otus"
        file: "src/content/pages/about.md"
        fields:
        - {label: "Template", name: "template", widget: "hidden", default: "about-page" }
        - {label: "Slug", name: "slug", widget: "hidden", default: "/about" }
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
      - label: "Ota Yhteyttä"
        name: "Ota Yhteyttä"
        file: "src/content/pages/contact.md"
        fields:
        - {label: "Template", name: "template", widget: "hidden", default: "contact-page" }
        - {label: "Slug", name: "slug", widget: "hidden", default: "/contact-page" }
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
  - name: settings
    label: Settings
    files:
      - name: general
        label: General
        file: "config.js"
        fields:
          - label: meta
            name: meta
            widget: object
            fields:
              - widget: string
                name: title
                label: Site Title
                required: true
              - widget: string
                name: titleTemplate
                label: Title Template
                default: "%s"
                required: true
              - widget: string
                name: siteUrl
                label: Website URL
                required: true
              - widget: text
                name: description
                label: Description
                default: ''
                required: false
              - widget: image
                name: image
                label: image
                default: '/assets/stackrole.png'
              - widget: image
                name: iconimage
                label: favicon
              - widget: string
                name: twitterUsername
                label: Twitter
                required: false
                
          - label: "Google Tag Manager"
            name: gtm
            widget: string
            hint: "Add you tracking ID, for example GTM-XXXXX-X"
